name: Publish And Deploy Demo
on: # 此CI/CD触发时的事件
  push: # 在代码提交时自动触发
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # 下载源码
    - name: Checkout
      uses: actions/checkout@master

    # 打包构建
    - name: Build
      uses: actions/setup-node@master
    - run: npm install
    - run: npm run build

    # 部署到服务器
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
          # 本地.ssh文件下的私钥id_rsa，存在secrets的TOKEN中
          SSH_PRIVATE_KEY: ${{ secrets.P_TOKEN }} 
          # 复制操作的参数。"-avzr --delete"意味部署时清空服务器目标目录下的文件
          ARGS: "-avzr --delete" 
          # 源目录，相对于$GITHUB_WORKSPACE根目录的路径
          SOURCE: "./docs/.vuepress/dist/" 
          # 服务器域名
          REMOTE_HOST: ${{ secrets.HOST }}
          # 腾讯云默认用户名为root
          REMOTE_USER: ${{ secrets.PORT }} 
          # 目标目录
          TARGET: "/var/wwww/html/" 
          

