name: Publish And Deploy Demo
on: # 此CI/CD触发时的事件
  push: # 在代码提交时自动触发
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # 下载源码
    - name: Checkout
      uses: actions/checkout@master

    # 打包构建
    - name: Build
      uses: actions/setup-node@master
    - run: npm install
    - run: npm run build

    # 命名这个任务为发布Deploy
    - name: Deploy
      uses: cross-the-world/scp-pipeline@master
      env:
        WELCOME: "ssh scp ssh pipelines"
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        pass: ${{ secrets.PASSWORD }}
        connect_timeout: 10s
        local: './dist/.vuepress/dist'
        remote: /var/www/html
